compressionLevel: mixed
enableGlobalCache: false
nodeLinker: pnp
packageExtensions:
  "@types/express@*":
    dependencies:
      body-parser: "*"
      serve-static: "*"
  "@types/express-serve-static-core@*":
    dependencies:
      events: "*"
      qs: "*"
      range-parser: "*"
      send: "*"
  "@types/node@*":
    dependencies:
      buffer: "*"
      events: "*"
      punycode: "*"
      string_decoder: "*"
  "@types/serve-static@*":
    dependencies:
      http-errors: "*"
      send: "*"
  "@types/send@*":
    dependencies:
      mime: "*"
  "@types/superagent@*":
    dependencies:
      buffer: "*"
      cookiejar: "*"
      methods: "*"
  "@types/supertest@*":
    dependencies:
      methods: "*"
      superagent: "*"
  "@vitejs/plugin-vue@*":
    peerDependencies:
      supports-color: "*"
  "@vue/compiler-sfc@*":
    dependencies:
      pug: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  undici-types@*:
    dependencies:
      buffer: "*"
      events: "*"
  unplugin-vue-router@*:
    peerDependencies:
      "@vue/compiler-sfc": "*"
  vite@*:
    peerDependencies:
      supports-color: "*"
  vue-loader@*:
    peerDependencies:
      "@vue/compiler-sfc": "*"
      webpack: "*"
pnpMode: loose
