enableGlobalCache: false
nodeLinker: pnp
packageExtensions:
  "@vitejs/plugin-vue@*":
    peerDependencies:
      supports-color: "*"
  "@vue/compiler-sfc@*":
    dependencies:
      pug: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  unplugin-vue-router@*:
    peerDependencies:
      "@vue/compiler-sfc": "*"
  vite@*:
    peerDependencies:
      supports-color: "*"
  vue-loader@*:
    peerDependencies:
      "@vue/compiler-sfc": "*"
      webpack: "*"
pnpMode: loose
