services:
  keystone-app:
    build:
      context: nm-packages/keystone-app
    command:
      - yarn
      - dev
    depends_on:
      - postgres
    environment:
      DATABASE_PROVIDER: postgresql
      DATABASE_URL: postgres://example:example@postgres:5432/keystone
      DATABASE_ENABLE_LOGGING: "true"
      VIRTUAL_HOST: keystone.local
      VIRTUAL_PORT: "3003"
    image: example-keystone-app
    ports:
      - 3003:3003
    volumes:
      - "./nm-packages/keystone-app:/keystone-app:rw"
      - /keystone-app/.keystone
      # - /keystone-app/.yarn

  nest-app:
    build:
      context: .
    command:
      - start:dev
    environment:
      WORKSPACE_NAME: nest-app
    image: example-monoservice
    ports:
      - 3001:3000
    volumes:
      - .:/monorepo:rw
      # - /monorepo/.yarn
      # - nest-app_dist:/monorepo/packages/nest-app/dist:rw

  vue-app:
    build:
      context: .
    command:
      - dev
    environment:
      WORKSPACE_NAME: vue-app
    image: example-monoservice
    ports:
      - 3002:3000
    volumes:
      - .:/monorepo:rw
      # - /monorepo/.yarn
      # - vue-app_dist:/monorepo/packages/vue-app/dist:rw
  postgres:
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
      - 5433:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
# volumes:
#   nest-app_dist: null
#   vue-app_dist: null
